### ISSUE TITLE
1.11.2-0.1.1 crashes dedicated Forge 1.11.2 build 2201 on startup

### ISSUE THREAD

**Issue by kreezxil** [AtomicBlom/HomecraftMineware#3] opened 2017-01-04 14:25 UTC
crash report:
https://gist.github.com/e6f07099b5c7ae4f81530baca5ef387e

fml server latest:
https://gist.github.com/01546e9a27eb7b5275a4d2d728bf16a9

**Comment by AtomicBlom** [comment] 2017-01-05 01:57
Should be fixed in 0.1.2, once it gets approved.

I fixed a bug in Structure, that was relying on a Client-side library. Not reproducable in dev because the client library is there -_-

**Closed as completed** 2017-01-11 06:08 UTC
