### ISSUE TITLE
Why are you embedding CompatLayer?

### ISSUE THREAD

**Issue by brisingraerowing** [AtomicBlom/HomecraftMineware#7] opened 2017-01-16 16:00 UTC
All that does is create major incompatibilities with other mods that use later versions of it, including RFTools, which I use.

You need to have CompatLayer as a dependency, not as an embedded library.

@McJty

**Comment by AtomicBlom** [comment] 2017-01-17 00:32
The main benefit of compatlayer is the idea that you can create a version-agnostic version of your mod .jar

In practice, in order for this to be a reality, compatlayer needs to be the base class of your blocks, which is not feasible as I'm using Structure, which also wants to be the base class of my multiblock blocks, so short of introducing compatlayer to Structure, which I'm not sure FoudroyantFactotum wants to do, I don't get the benefit of having a fully portable .jar.

So given that I can't use compatlayer as intended, the thing I'm really using compatlayer for is the utilities around item stack handling, and it didn't seem worthwhile making someone download an entirely separate dependency for that one little nicety on my part.

So then to discuss an actual solution to the issue, which I've been unable to recreate using downloads from curse, I am lead to guess that the issue is caused by my accidentally including the package-info.class while shading. I was not aware that compatlayer exposed itself as an API.

I believe that simply excluding the package-info will fix the issue.

**Comment by AtomicBlom** [comment] 2017-01-17 02:56
Can you please try this build to see if it fixes the problem?
http://builds.steamnsteel.info/browse/HCMW-BETA1-5/artifact/JOB1/Universal/hcmw-1.10.2-0.1.5-universal.jar

**Comment by apotheoseGrifter** [comment] 2017-01-18 04:09
I'm not a coder, so I don't fully understand anything you just said, but it seems to me that it goes against the whole spirit of an API to use one like this. Doesn't that mean that code will be duplicated whenever someone downloads the dependency for use with other mods that use compatlayer more extensively? Especially if the versions are incompatible? Seems likely to cause more compatibility issues in the future, not lessen them. It would be nice if your Curse page at least listed compatlayer as an embedded library, though. I never would've guessed a mod that seemingly had nothing to do with compatlayer was causing all these issues with RFTools rejecting it.

In any case, the new version does seem to fix this particular issue, even when used with the latest version on the jenkins. I can't be completely positive, since I have yet to finish resolving a (hopefully) unrelated crash.

**Comment by AtomicBlom** [comment] 2017-01-18 04:56
Thanks for having a preliminary test, I'd love to hear how you went.

You are correct in that it introduces duplicate code, but to be honest, I'm not concerned about the impact. We're talking about 3-4k of memory and 120k of disk space. (Since I don't use all the classes, even though I package the whole lot)

In terms of decreasing compatibility, now that my embedded version doesn't expose itself to any other mods, it's more likely to increase compatibility, since if @McJty introduces a breaking change to compatlayer, it won't break Homecraft Mineware, and I can update at my own pace rather than having everyone hounding me to update to fix a crash caused by an updated compatlayer.

I don't believe this goes against the spirit of an API to embed it like this, as my use of compatlayer is less about sharing code with other mods, and instead promoting code reuse, I can benefit from any bug fixes contributed to compatlayer without having to maintain my own copy of what it does.

I won't go as far as listing compatlayer as a dependency on curse (because that would force everyone to download the separate file), but I might mention it in the description.

Before going down this path, I spoke with @McJty about the pros and cons of it, and neither of us realised that the @API annotation would cause issues. We're both aware of the issue, and I will probably PR some documentation to compatlayer to warn others of the potential dangers.

**Comment by brisingraerowing** [comment] 2017-01-22 01:28
Sorry for the late reply. I can't get MC to load for some reason (something about corrupted NBT).

Well, it gets to the main menu, then loading worlds crash within a few seconds. Vanilla works, so it is a Mod, but it worked the day before with the same mods and same versions. Even creating a new world crashes.

As I have 212 Mods, it may take a while to figure out what happened.

**Comment by brisingraerowing** [comment] 2017-01-22 01:30
And I just got it working. I cleared out my Mods directory, loaded MC, closed it, readded the mods, and launched it again.

Go figure.

I did a refresh of my mods, and I'll have to see how many block IDs I have left.

**Comment by brisingraerowing** [comment] 2017-01-22 01:41
And it seems to work. Didn't try to load a world, though.

**Comment by AtomicBlom** [comment] 2017-01-23 03:11
Fixed in 0.2.x

**Closed as completed by AtomicBlom** 2017-01-23 03:11 UTC
Labels: bug
